remote_agents:
  enabled: true
  cache_timeout: 120  # Cache timeout in minutes (2 hours)
  retry_attempts: 5   # Number of retry attempts
  retry_delay: 2000   # Delay between retries in milliseconds
  sources:
    individual:
      # Individual agent files
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/developer-agent.agent.md"
        alias: "developer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/validator-agent.agent.md"
        alias: "validator-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/build-fixer-agent.agent.md"
        alias: "build-fixer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/communication/content-writer-agent.agent.md"
        alias: "content-writer-agent"