defaults:
  cli_command: "printenv | cat - {{prompt_path}} | COLORBT_SHOW_HIDDEN=1 RUST_BACKTRACE=full CODEX_QUIET_MODE=1 codex exec --dangerously-bypass-approvals-and-sandbox -c model=codex-mini -c model_provider=azure -c model_providers.azure.name=azure -c model_providers.azure.wire_api=responses -c model_providers.azure.base_url=https://{{envs.AZURE_OPENAI_PROJECT_NAME}}.openai.azure.com/openai -c model_providers.azure.env_key=AZURE_OPENAI_API_KEY -c model_providers.azure.query_params.api-version=2025-04-01-preview --output-last-message /tmp/agent-output.md"


remote_agents:
  enabled: true
  cache_timeout: 120  # Cache timeout in minutes (2 hours)
  retry_attempts: 5   # Number of retry attempts
  retry_delay: 2000   # Delay between retries in milliseconds
  sources:
    individual:
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/developer-agent.agent.md"
        alias: "developer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/validator-agent.agent.md"
        alias: "validator-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/build-fixer-agent.agent.md"
        alias: "build-fixer-agent"

      # Content creation agents for documentation
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/communication/content-writer-agent.agent.md"
        alias: "content-writer-agent"
      # Research agents for documentation improvement
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/research/researcher-base-agent.agent.md"
        alias: "researcher-agent"

      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/team-installer-agent.agent.md"
        alias: "team-installer-agent"

      # Project orchestration and maintenance agents
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/producer-agent.agent.md"
        alias: "producer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/conflict-resolver-agent.agent.md"
        alias: "conflict-resolver-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/documenter-agent.agent.md"
        alias: "documenter-agent"
