remote_agents:
  enabled: true
  cache_timeout: 120  # 2 hours
  retry_attempts: 5
  retry_delay: 2000   # 2 seconds
  sources:
    individual:
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/developer-agent.agent.md"
        alias: "developer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/validator-agent.agent.md"
        alias: "validator-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/research/researcher-base-agent.agent.md"
        alias: "researcher-base-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/communication/content-writer-agent.agent.md"
        alias: "content-writer-agent"

# Override agent discovery settings
# agent_discovery:
#   enabled: true
#   max_agents_in_context: 15
#   include_same_directory: true

# Override prompt URI settings
# prompt_uri:
#   cache_timeout: 120
#   retry_attempts: 5
#   retry_delay: 2000 
